### ISSUE TITLE
Problème dev astro nav

### ISSUE THREAD

**Issue by Klaynight-dev** [DreamCloud-Development/vaatigames#1]
Sur le header quand on est sur les projet et qu'on clique sur developper puis codespace cela nous ammène à une erreur 404 car il nous emène ici https://vaatigames.ovh/projet/ticket/codespace

**Comment by Klaynight-dev** [comment]
ou https://vaatigames.ovh/projet/links/codespace

**Comment by Funasitien** [comment]
Fix in 382542c
